[package]
name = "x86intrin"
version = "0.2.0"
authors = ["mayah"]

license = "MIT/Apache-2.0"
keywords = ["simd", "sse", "avx", "x86intrin"]
readme = "README.md"
repository = "https://github.com/mayah/x86intrin"
description = "x86intrin implementation"

[dependencies]
